/**
 * Tabela de alimentos da NutriGLP.
 * Valores por 100 g de parte edível, tal como o alimento é habitualmente consumido
 * (o campo "estado" diz se é cru ou cozinhado). Aproximados, com base na Tabela de
 * Composição de Alimentos do INSA e em tabelas equivalentes; servem para calcular os
 * macros de cada refeição de forma consistente na própria página. Não substituem o
 * rótulo de um produto concreto.
 *
 * Campos: [nome, kcal, proteína g, hidratos g, gordura g, fibra g, { aliases, un, cs, cc, estado }]
 *   un  = gramas de 1 unidade (ovo, peça de fruta, pão…)
 *   cs  = gramas de 1 colher de sopa   ·   cc = gramas de 1 colher de chá
 */
window.NG_FOODS = [
  // ---------- carne e ovos ----------
  ["peito de frango", 110, 23, 0, 1.5, 0, { aliases: ["frango", "peito de frango cru", "frango cru"], estado: "cru" }],
  ["peito de frango grelhado", 165, 31, 0, 3.6, 0, { aliases: ["frango grelhado", "peito de frango cozinhado", "frango assado sem pele", "frango assado", "frango desfiado", "frango cozido", "frango no forno"], estado: "cozinhado" }],
  ["peito de peru", 105, 24, 0, 1, 0, { aliases: ["peru", "peru cru"], estado: "cru" }],
  ["peito de peru grelhado", 150, 30, 0, 2, 0, { aliases: ["peru grelhado", "peru cozinhado", "peru assado", "peru desfiado", "fiambre de peru"], estado: "cozinhado" }],
  ["lombo de porco", 130, 21, 0, 5, 0, { aliases: ["lombo de porco magro", "porco magro", "lombinho de porco", "carne de porco magra"], estado: "cru" }],
  ["lombo de porco grelhado", 175, 28, 0, 7, 0, { aliases: ["porco grelhado", "lombo de porco assado", "porco assado"], estado: "cozinhado" }],
  ["vitela magra", 130, 21, 0, 5, 0, { aliases: ["vitela", "carne de vaca magra", "vaca magra", "bife de vaca", "bife de vitela", "novilho", "carne vermelha magra"], estado: "cru" }],
  ["bife de vaca grelhado", 180, 28, 0, 7.5, 0, { aliases: ["vitela grelhada", "vaca grelhada", "carne de vaca cozinhada", "carne picada magra cozinhada"], estado: "cozinhado" }],
  ["carne picada magra", 140, 20, 0, 7, 0, { aliases: ["carne picada"], estado: "cru" }],
  ["fígado de vaca", 135, 20, 4, 4, 0, { aliases: ["fígado", "figado", "fígado de frango", "iscas"], estado: "cru" }],
  ["ovo", 145, 12.5, 0.7, 10, 0, { aliases: ["ovos", "ovo cozido", "ovos cozidos", "ovo escalfado", "ovo inteiro", "ovo m", "ovo l"], un: 55, estado: "cru ou cozido" }],
  ["ovos mexidos", 160, 12, 1, 12, 0, { aliases: ["ovo mexido", "omelete", "omelete simples", "omelete de 2 ovos", "omelete de claras e ovo"], un: 60, estado: "cozinhado" }],
  ["clara de ovo", 48, 11, 0.7, 0, 0, { aliases: ["claras", "claras de ovo", "clara"], un: 33, estado: "cru" }],
  // ---------- peixe e marisco ----------
  ["pescada", 75, 17, 0, 0.7, 0, { aliases: ["pescada crua", "filete de pescada", "filetes de pescada"], estado: "cru" }],
  ["pescada cozida", 90, 20, 0, 1, 0, { aliases: ["pescada grelhada", "pescada no forno", "pescada cozinhada", "pescada assada"], estado: "cozinhado" }],
  ["bacalhau demolhado", 80, 18, 0, 0.7, 0, { aliases: ["bacalhau", "bacalhau cru", "bacalhau cru/demolhado", "lombo de bacalhau"], estado: "cru" }],
  ["bacalhau cozido", 95, 21, 0, 1, 0, { aliases: ["bacalhau grelhado", "bacalhau assado", "bacalhau no forno", "bacalhau desfiado", "bacalhau cozinhado"], estado: "cozinhado" }],
  ["sardinha", 160, 19, 0, 9.5, 0, { aliases: ["sardinhas", "sardinha crua", "sardinha fresca"], un: 60, estado: "cru" }],
  ["sardinha assada", 200, 24, 0, 11, 0, { aliases: ["sardinhas assadas", "sardinha grelhada", "sardinhas grelhadas", "sardinha em lata", "sardinha de lata", "sardinhas em conserva", "sardinha em conserva"], un: 50, estado: "cozinhado" }],
  ["carapau", 105, 19, 0, 3, 0, { aliases: ["carapaus", "carapau grelhado", "carapau assado", "carapau cozido"], estado: "cru" }],
  ["cavala", 190, 19, 0, 13, 0, { aliases: ["cavala grelhada", "cavala assada", "cavala em lata", "cavala em conserva", "sarda"], estado: "cru" }],
  ["dourada", 100, 19, 0, 2.5, 0, { aliases: ["dourada grelhada", "dourada assada", "robalo", "robalo grelhado", "robalo assado", "peixe branco", "peixe branco grelhado", "linguado", "solha"], estado: "cru" }],
  ["salmão", 190, 20, 0, 12, 0, { aliases: ["salmão cru", "salmao", "lombo de salmão"], estado: "cru" }],
  ["salmão grelhado", 210, 23, 0, 13, 0, { aliases: ["salmão assado", "salmão no forno", "salmão cozinhado", "salmão fumado"], estado: "cozinhado" }],
  ["atum em água", 105, 24, 0, 1, 0, { aliases: ["atum", "atum ao natural", "atum em lata", "atum de lata", "atum em conserva", "atum escorrido", "atum em água escorrido", "lata de atum"], un: 85, estado: "escorrido" }],
  ["atum fresco", 110, 24, 0, 1, 0, { aliases: ["atum grelhado", "bife de atum", "atum fresco grelhado"], estado: "cru" }],
  ["polvo cozido", 80, 16, 2, 1, 0, { aliases: ["polvo", "polvo grelhado", "polvo à lagareiro", "salada de polvo"], estado: "cozinhado" }],
  ["camarão cozido", 90, 20, 0, 1, 0, { aliases: ["camarão", "camarões", "gambas", "camarão descascado", "miolo de camarão"], estado: "cozinhado" }],
  ["amêijoa cozida", 85, 14, 3, 2, 0, { aliases: ["amêijoa", "amêijoas", "ameijoa", "berbigão", "mexilhão", "mexilhões", "bivalves", "miolo de mexilhão"], estado: "cozinhado" }],
  ["lulas", 90, 16, 3, 1.5, 0, { aliases: ["lula", "lulas grelhadas", "choco", "chocos"], estado: "cru" }],
  // ---------- lacticínios e alternativas ----------
  ["leite meio-gordo", 47, 3.3, 4.8, 1.6, 0, { aliases: ["leite", "leite meio gordo"], un: 250, cs: 15, estado: "líquido" }],
  ["leite magro", 35, 3.4, 4.9, 0.2, 0, { aliases: ["leite desnatado", "leite 0%"], un: 250, cs: 15, estado: "líquido" }],
  ["bebida de soja", 40, 3.5, 1.5, 2, 0.5, { aliases: ["leite de soja", "bebida vegetal de soja"], un: 250, estado: "líquido" }],
  ["bebida de amêndoa", 15, 0.5, 1, 1.2, 0.3, { aliases: ["leite de amêndoa", "bebida vegetal", "bebida de aveia", "leite de aveia"], un: 250, estado: "líquido" }],
  ["iogurte natural", 60, 4, 5.5, 2.5, 0, { aliases: ["iogurte", "iogurte natural sem açúcar", "iogurte natural inteiro"], un: 125, estado: "pronto a consumir" }],
  ["iogurte natural magro", 45, 4.5, 5, 0.3, 0, { aliases: ["iogurte magro", "iogurte 0%", "iogurte natural 0%", "iogurte líquido magro"], un: 125, estado: "pronto a consumir" }],
  ["iogurte grego natural", 97, 5, 3.8, 7.5, 0, { aliases: ["iogurte grego", "iogurte tipo grego", "iogurte grego inteiro"], un: 150, estado: "pronto a consumir" }],
  ["iogurte grego natural 0%", 60, 10, 4, 0.2, 0, { aliases: ["iogurte grego magro", "iogurte grego 0%", "iogurte grego natural magro", "iogurte grego natural 0 %", "iogurte proteico", "iogurte rico em proteína"], un: 150, estado: "pronto a consumir" }],
  ["skyr natural", 62, 11, 4, 0.2, 0, { aliases: ["skyr", "skyr natural sem açúcar", "skyr magro"], un: 150, estado: "pronto a consumir" }],
  ["kefir", 55, 3.5, 4, 2.5, 0, { aliases: ["kefir natural"], un: 200, estado: "líquido" }],
  ["queijo fresco magro", 70, 12, 3, 1.5, 0, { aliases: ["queijo fresco", "queijo fresco light", "queijo fresco de vaca", "queijo fresco batido", "queijo quark", "quark"], un: 200, estado: "pronto a consumir" }],
  ["requeijão", 150, 11, 3, 10, 0, { aliases: ["requeijão de ovelha", "requeijao"], un: 200, estado: "pronto a consumir" }],
  ["requeijão magro", 90, 12, 3, 3, 0, { aliases: ["requeijão light", "requeijão de vaca magro"], un: 200, estado: "pronto a consumir" }],
  ["queijo flamengo", 350, 24, 0, 28, 0, { aliases: ["queijo", "queijo flamengo light", "queijo fatiado", "fatia de queijo", "queijo de vaca", "queijo mozarela", "mozarela", "mozzarella"], un: 20, estado: "pronto a consumir" }],
  ["queijo curado", 400, 25, 0, 33, 0, { aliases: ["queijo da serra", "queijo de ovelha", "queijo de cabra", "queijo parmesão", "parmesão", "queijo ralado"], un: 20, estado: "pronto a consumir" }],
  ["queijo feta", 265, 14, 4, 21, 0, { aliases: ["feta"], estado: "pronto a consumir" }],
  ["manteiga", 740, 0.5, 0, 82, 0, { aliases: ["manteiga com sal", "manteiga sem sal", "manteiga derretida"], cs: 15, cc: 5, estado: "pronto a consumir" }],
  ["natas", 300, 2, 3, 30, 0, { aliases: ["natas para culinária", "natas light"], cs: 15, estado: "líquido" }],
  // ---------- leguminosas e proteína vegetal ----------
  ["grão-de-bico cozido", 145, 8.5, 22, 2.5, 6, { aliases: ["grão-de-bico", "grão de bico", "grão", "grão cozido", "grão-de-bico em conserva", "grão-de-bico salteado", "grão de bico cozido"], cs: 27, estado: "cozinhado" }],
  ["feijão cozido", 110, 7.5, 18, 0.5, 6.5, { aliases: ["feijão", "feijão encarnado", "feijão branco", "feijão preto", "feijão catarino", "feijão manteiga", "feijão frade", "feijão em conserva", "feijão cozido escorrido"], cs: 27, estado: "cozinhado" }],
  ["lentilhas cozidas", 110, 9, 17, 0.5, 6, { aliases: ["lentilhas", "lentilha", "lentilhas em conserva", "lentilhas vermelhas cozidas"], cs: 27, estado: "cozinhado" }],
  ["ervilhas cozidas", 80, 5, 12, 0.5, 5, { aliases: ["ervilhas", "ervilha", "ervilhas congeladas"], cs: 20, estado: "cozinhado" }],
  ["favas cozidas", 90, 7, 12, 0.5, 5, { aliases: ["favas", "fava"], cs: 25, estado: "cozinhado" }],
  ["tremoços", 120, 16, 7, 2.5, 5, { aliases: ["tremoço"], estado: "escorrido" }],
  ["húmus", 170, 7, 14, 9, 5, { aliases: ["hummus", "humus", "pasta de grão"], cs: 25, estado: "pronto a consumir" }],
  ["tofu", 120, 12, 2, 7, 1, { aliases: ["tofu firme", "tofu grelhado"], estado: "cru" }],
  ["soja texturizada hidratada", 95, 15, 5, 1, 4, { aliases: ["soja", "soja texturizada"], estado: "cozinhado" }],
  ["edamame", 120, 11, 9, 5, 5, { aliases: ["feijão de soja verde"], estado: "cozinhado" }],
  // ---------- cereais, pão e tubérculos ----------
  ["arroz integral cozido", 125, 2.6, 26, 1, 1.8, { aliases: ["arroz integral", "arroz integral cozinhado"], cs: 27, estado: "cozinhado" }],
  ["arroz integral cru", 360, 7.5, 76, 2.7, 3.5, { aliases: ["arroz integral seco"], cs: 17, estado: "cru" }],
  ["arroz branco cozido", 130, 2.5, 28, 0.3, 0.4, { aliases: ["arroz", "arroz branco", "arroz cozido", "arroz basmati", "arroz basmati cozido", "arroz carolino"], cs: 27, estado: "cozinhado" }],
  ["arroz branco cru", 355, 7, 79, 0.6, 1, { aliases: ["arroz cru", "arroz seco"], cs: 17, estado: "cru" }],
  ["massa integral cozida", 130, 5.5, 26, 1, 4, { aliases: ["massa integral", "esparguete integral", "esparguete integral cozido", "massa integral cozinhada", "penne integral"], cs: 27, estado: "cozinhado" }],
  ["massa cozida", 140, 5, 28, 1, 1.5, { aliases: ["massa", "esparguete", "esparguete cozido", "macarrão", "massa cozinhada", "penne"], cs: 27, estado: "cozinhado" }],
  ["massa crua", 360, 12, 72, 1.5, 3, { aliases: ["massa seca", "massa integral crua", "esparguete cru"], estado: "cru" }],
  ["quinoa cozida", 120, 4.4, 21, 2, 2.8, { aliases: ["quinoa", "quinoa cozinhada"], cs: 25, estado: "cozinhado" }],
  ["cuscuz cozido", 110, 3.8, 23, 0.2, 1.4, { aliases: ["cuscuz", "couscous"], cs: 25, estado: "cozinhado" }],
  ["aveia", 375, 13, 60, 7, 10, { aliases: ["flocos de aveia", "aveia integral", "aveia em flocos", "aveia fina", "farinha de aveia", "aveia crua", "aveia seca"], cs: 10, estado: "cru" }],
  ["papas de aveia", 70, 2.5, 11, 1.5, 1.8, { aliases: ["papas de aveia com água", "porridge"], estado: "cozinhado" }],
  ["pão integral", 245, 9, 45, 2.5, 6, { aliases: ["pão de trigo integral", "pão integral de forma", "fatia de pão integral", "pão de sementes", "pão escuro"], un: 50, estado: "pronto a consumir" }],
  ["pão de centeio", 230, 7, 45, 1.5, 7, { aliases: ["pão de centeio escuro", "centeio", "fatia de pão de centeio", "pão de centeio integral"], un: 50, estado: "pronto a consumir" }],
  ["pão de mistura", 270, 8.5, 54, 1.5, 3, { aliases: ["pão", "papo-seco", "papo seco", "carcaça", "pão branco", "pão de trigo", "pão de forma", "pão alentejano", "bolo do caco", "pão de água"], un: 50, estado: "pronto a consumir" }],
  ["broa de milho", 250, 6, 50, 2, 3, { aliases: ["broa", "fatia de broa"], un: 50, estado: "pronto a consumir" }],
  ["torrada integral", 260, 10, 48, 2.5, 6, { aliases: ["torrada", "torradas integrais", "torradas", "pão integral torrado", "fatia de pão integral torrada", "torrada de pão integral"], un: 25, estado: "tostada" }],
  ["tostas integrais", 380, 12, 68, 5, 8, { aliases: ["tosta integral", "tostas", "tosta", "tostas de trigo integral", "tosta de centeio", "tostas de centeio", "bolacha de água e sal", "bolachas de água e sal", "tostas de arroz", "galetes de arroz", "galete de arroz", "galete de milho"], un: 8, estado: "pronto a consumir" }],
  ["bolacha maria", 430, 7, 75, 12, 2, { aliases: ["bolachas maria", "bolacha", "bolachas"], un: 6, estado: "pronto a consumir" }],
  ["cereais integrais de pequeno-almoço", 370, 9, 75, 2, 9, { aliases: ["cereais integrais", "cereais de pequeno-almoço", "flocos de milho", "muesli", "muesli sem açúcar", "granola", "granola sem açúcar"], cs: 7, estado: "pronto a consumir" }],
  ["batata cozida", 80, 2, 17, 0.1, 1.6, { aliases: ["batata", "batatas", "batata cozida com pele", "batata a murro", "batata assada", "batata no forno", "batatas cozidas", "puré de batata"], un: 85, estado: "cozinhado" }],
  ["batata-doce cozida", 90, 1.5, 20, 0.1, 3, { aliases: ["batata-doce", "batata doce", "batata-doce assada", "batata doce assada", "batata-doce no forno", "batata-doce cozida com pele", "puré de batata-doce", "puré de courgette e batata-doce"], un: 150, estado: "cozinhado" }],
  ["milho doce cozido", 95, 3, 18, 1.5, 2.5, { aliases: ["milho", "milho doce", "milho em conserva"], cs: 15, estado: "cozinhado" }],
  // ---------- hortícolas ----------
  ["brócolos cozidos", 35, 3, 4, 0.4, 3, { aliases: ["brócolos", "brócolo", "brocolos", "brócolos a vapor", "brócolos salteados", "cenoura e brócolos"], estado: "cozinhado" }],
  ["couve-flor cozida", 25, 2, 3, 0.3, 2.5, { aliases: ["couve-flor", "couve flor"], estado: "cozinhado" }],
  ["couve galega cozida", 30, 2.5, 3, 0.5, 3, { aliases: ["couve galega", "couve portuguesa", "couve", "couve lombarda", "couve coração", "couve-de-bruxelas", "couves de bruxelas", "couve roxa", "couve branca", "repolho"], estado: "cozinhado" }],
  ["grelos cozidos", 25, 3, 2, 0.4, 3, { aliases: ["grelos", "nabiças", "nabiça", "grelos salteados"], estado: "cozinhado" }],
  ["espinafres cozidos", 25, 3, 1.5, 0.5, 2.5, { aliases: ["espinafres", "espinafre", "espinafres salteados", "espinafres a vapor", "esparregado", "salada de espinafres", "espinafres crus", "espinafres baby"], estado: "cozinhado" }],
  ["courgette cozida", 20, 1.3, 2.5, 0.3, 1.2, { aliases: ["courgette", "curgete", "courgette grelhada", "courgette salteada", "abobrinha"], estado: "cozinhado" }],
  ["cenoura", 35, 0.8, 7, 0.2, 3, { aliases: ["cenouras", "cenoura cozida", "cenoura ralada", "cenoura crua", "cenoura baby", "cenoura em palitos"], un: 80, estado: "cru ou cozinhado" }],
  ["tomate", 20, 0.9, 3, 0.2, 1.2, { aliases: ["tomates", "tomate maduro", "tomate em rodelas", "tomate fresco"], un: 120, estado: "cru" }],
  ["tomate cherry", 20, 0.9, 3, 0.2, 1.2, { aliases: ["tomates cherry", "tomate-cereja", "tomate cereja"], un: 15, estado: "cru" }],
  ["pepino", 14, 0.7, 2.5, 0.1, 0.7, { aliases: ["pepinos", "pepino em rodelas"], un: 200, estado: "cru" }],
  ["alface", 15, 1.3, 2, 0.2, 1.5, { aliases: ["salada verde", "salada de alface", "folhas verdes", "mix de folhas", "rúcula", "agrião", "canónigos", "salada de folhas"], estado: "cru" }],
  ["salada mista", 18, 1.2, 3, 0.2, 1.5, { aliases: ["salada", "salada de tomate e pepino", "salada de tomate, pepino e cebola", "salada de tomate", "salada de legumes", "salada variada", "salada crua", "legumes crus"], estado: "cru" }],
  ["cebola", 40, 1.1, 9, 0.1, 1.7, { aliases: ["cebolas", "cebola roxa", "cebola refogada", "chalota"], un: 100, estado: "cru" }],
  ["alho", 140, 6, 30, 0.5, 2, { aliases: ["dente de alho", "dentes de alho", "alho picado"], un: 3, estado: "cru" }],
  ["pimento", 26, 1, 5, 0.3, 2, { aliases: ["pimentos", "pimento vermelho", "pimento verde", "pimento assado", "pimentos assados"], un: 150, estado: "cru" }],
  ["feijão-verde cozido", 30, 1.8, 5, 0.2, 3, { aliases: ["feijão verde", "feijão-verde", "vagens"], estado: "cozinhado" }],
  ["abóbora cozida", 25, 1, 5, 0.1, 1.5, { aliases: ["abóbora", "abobora", "abóbora assada", "puré de abóbora"], estado: "cozinhado" }],
  ["beringela", 25, 1, 5, 0.2, 3, { aliases: ["beringela grelhada", "beringela assada", "berinjela"], estado: "cozinhado" }],
  ["cogumelos", 22, 3, 3, 0.3, 1.5, { aliases: ["cogumelo", "cogumelos salteados", "cogumelos frescos", "cogumelos laminados", "cogumelos portobello", "shiitake"], estado: "cru ou cozinhado" }],
  ["espargos", 20, 2.2, 2, 0.2, 2, { aliases: ["espargo", "espargos verdes", "espargos grelhados"], estado: "cozinhado" }],
  ["alho-francês", 30, 1.5, 5, 0.3, 2, { aliases: ["alho francês", "alho-porro"], estado: "cozinhado" }],
  ["beterraba cozida", 45, 1.7, 9, 0.2, 2.5, { aliases: ["beterraba"], estado: "cozinhado" }],
  ["legumes salteados", 60, 2, 6, 3, 2.5, { aliases: ["legumes salteados (courgette, cenoura)", "salteado de legumes", "legumes salteados em azeite", "mistura de legumes salteados", "wok de legumes"], estado: "cozinhado" }],
  ["legumes cozidos", 35, 2, 5, 0.3, 2.5, { aliases: ["legumes", "legumes a vapor", "legumes mistos", "mistura de legumes", "legumes cozidos a vapor", "hortícolas cozidos", "hortícolas", "legumes grelhados", "legumes assados", "legumes no forno"], estado: "cozinhado" }],
  ["sopa de legumes", 40, 1.5, 6, 1, 1.5, { aliases: ["sopa", "sopa de legumes sem batata", "sopa de hortícolas", "creme de legumes", "sopa de legumes caseira", "sopa de legumes passada", "sopa de couve", "sopa de abóbora", "sopa de cenoura", "caldo verde"], un: 250, estado: "pronta" }],
  ["sopa de legumes com feijão", 60, 3, 9, 1, 2.5, { aliases: ["sopa de feijão", "sopa de grão", "sopa de legumes com grão", "sopa de legumes com leguminosas", "sopa de lentilhas", "sopa rica"], un: 250, estado: "pronta" }],
  ["canja", 45, 4, 5, 1, 0.3, { aliases: ["canja de galinha", "sopa de galinha", "caldo de galinha com massa", "sopa de frango"], un: 250, estado: "pronta" }],
  ["caldo de legumes", 15, 1, 2, 0.4, 0.3, { aliases: ["caldo", "caldo caseiro", "caldo de carne", "caldo de galinha", "caldo morno", "caldo salgado"], un: 250, estado: "líquido" }],
  ["sopa de peixe", 55, 6, 4, 1.5, 1, { aliases: ["sopa de peixe com legumes", "caldeirada de peixe", "caldeirada"], un: 250, estado: "pronta" }],
  ["molho de tomate", 30, 1.5, 5, 0.5, 1.5, { aliases: ["polpa de tomate", "tomate em polpa", "tomate triturado", "tomate pelado"], cs: 15, estado: "pronto a consumir" }],
  // ---------- fruta ----------
  ["maçã", 52, 0.3, 12, 0.2, 2.2, { aliases: ["maça", "maca", "maçã com casca", "maçã assada", "maçã cozida", "maçã ralada"], un: 160, estado: "cru" }],
  ["pera", 55, 0.4, 12.5, 0.1, 3, { aliases: ["pêra", "pera rocha"], un: 160, estado: "cru" }],
  ["banana", 90, 1.1, 20, 0.3, 2, { aliases: ["banana madura", "banana pequena"], un: 120, estado: "cru" }],
  ["laranja", 45, 0.9, 9, 0.2, 2, { aliases: ["laranjas", "laranja em gomos"], un: 170, estado: "cru" }],
  ["tangerina", 45, 0.8, 9, 0.2, 1.8, { aliases: ["clementina", "clementinas", "tangerinas"], un: 70, estado: "cru" }],
  ["kiwi", 55, 1, 11, 0.5, 2.5, { aliases: ["kiwis", "quivi"], un: 80, estado: "cru" }],
  ["morangos", 32, 0.7, 6, 0.3, 2, { aliases: ["morango"], un: 15, estado: "cru" }],
  ["mirtilos", 55, 0.7, 12, 0.3, 2.4, { aliases: ["mirtilo"], estado: "cru" }],
  ["framboesas", 45, 1.2, 6, 0.5, 6.5, { aliases: ["framboesa", "amoras", "frutos vermelhos", "frutos silvestres", "mistura de frutos vermelhos"], estado: "cru" }],
  ["uvas", 68, 0.6, 16, 0.2, 0.9, { aliases: ["uva"], estado: "cru" }],
  ["pêssego", 40, 0.9, 8, 0.2, 1.6, { aliases: ["pessego", "nectarina", "alperce", "damasco"], un: 150, estado: "cru" }],
  ["ameixa", 45, 0.7, 10, 0.2, 1.5, { aliases: ["ameixas", "ameixa fresca"], un: 60, estado: "cru" }],
  ["ameixa seca", 220, 2, 50, 0.4, 7, { aliases: ["ameixas secas"], un: 10, estado: "seca" }],
  ["melancia", 30, 0.6, 7, 0.2, 0.4, { aliases: ["fatia de melancia"], estado: "cru" }],
  ["melão", 30, 0.8, 6.5, 0.2, 0.8, { aliases: ["meloa", "fatia de melão"], estado: "cru" }],
  ["abacate", 160, 2, 2, 15, 6.7, { aliases: ["meio abacate"], un: 150, estado: "cru" }],
  ["figo", 65, 0.8, 14, 0.3, 2.5, { aliases: ["figos"], un: 50, estado: "cru" }],
  ["manga", 60, 0.8, 13, 0.3, 1.6, { aliases: ["papaia", "papaya", "ananás", "ananas", "abacaxi"], un: 150, estado: "cru" }],
  ["romã", 80, 1.5, 15, 1, 4, { aliases: ["bagos de romã"], estado: "cru" }],
  ["limão", 25, 0.4, 6, 0.2, 0.3, { aliases: ["sumo de limão", "limão espremido", "lima"], cs: 15, un: 60, estado: "cru" }],
  ["fruta da época", 50, 0.7, 11, 0.2, 2, { aliases: ["fruta", "peça de fruta", "fruta fresca", "salada de fruta", "fruta variada"], un: 160, estado: "cru" }],
  // ---------- gorduras, frutos secos e sementes ----------
  ["azeite", 900, 0, 0, 100, 0, { aliases: ["azeite virgem extra", "azeite extra virgem", "azeite em cru", "fio de azeite"], cs: 10, cc: 4, estado: "cru" }],
  ["óleo vegetal", 900, 0, 0, 100, 0, { aliases: ["óleo", "óleo de girassol", "óleo de coco"], cs: 10, cc: 4, estado: "cru" }],
  ["noz", 650, 15, 7, 64, 6.5, { aliases: ["nozes", "miolo de noz", "meia noz", "nozes ao natural"], un: 5, estado: "cru" }],
  ["amêndoa", 600, 21, 9, 50, 12, { aliases: ["amêndoas", "amendoa", "amendoas", "amêndoas ao natural", "amêndoa com pele", "amêndoas torradas", "amêndoa laminada"], un: 1.2, estado: "cru" }],
  ["avelã", 630, 15, 7, 60, 9, { aliases: ["avelãs"], un: 1.5, estado: "cru" }],
  ["caju", 570, 18, 30, 44, 3, { aliases: ["cajus", "castanha de caju"], un: 1.5, estado: "cru" }],
  ["amendoim", 570, 26, 16, 48, 8, { aliases: ["amendoins", "amendoim sem sal"], un: 1, estado: "cru" }],
  ["frutos secos", 600, 18, 12, 52, 8, { aliases: ["mistura de frutos secos", "frutos secos ao natural", "frutos oleaginosos", "mix de frutos secos"], estado: "cru" }],
  ["manteiga de amendoim", 600, 25, 20, 50, 6, { aliases: ["pasta de amendoim", "creme de amendoim", "manteiga de amêndoa", "pasta de amêndoa"], cs: 15, cc: 6, estado: "pronto a consumir" }],
  ["sementes de chia", 490, 17, 42, 31, 34, { aliases: ["chia", "semente de chia"], cs: 10, cc: 4, estado: "cru" }],
  ["sementes de linhaça", 530, 18, 29, 42, 27, { aliases: ["linhaça", "linhaça moída", "sementes de linhaça moída"], cs: 10, cc: 4, estado: "cru" }],
  ["sementes de abóbora", 560, 30, 11, 49, 6, { aliases: ["pevides", "sementes de girassol", "sementes de sésamo", "sésamo", "mistura de sementes", "sementes"], cs: 10, cc: 4, estado: "cru" }],
  ["azeitonas", 145, 1, 3, 15, 3.5, { aliases: ["azeitona", "azeitonas pretas", "azeitonas verdes"], un: 4, estado: "pronto a consumir" }],
  ["coco ralado", 660, 6, 23, 65, 14, { aliases: ["coco"], cs: 8, estado: "seco" }],
  // ---------- outros ----------
  ["canela", 250, 4, 80, 1, 53, { aliases: ["canela em pó", "canela moída", "pitada de canela"], cs: 8, cc: 2.5, estado: "seco" }],
  ["mel", 300, 0.3, 82, 0, 0, { aliases: ["mel puro"], cs: 20, cc: 7, estado: "pronto a consumir" }],
  ["açúcar", 400, 0, 100, 0, 0, { aliases: ["açúcar branco", "açúcar amarelo", "açúcar de coco"], cs: 12, cc: 4, estado: "seco" }],
  ["chocolate preto", 570, 8, 40, 40, 10, { aliases: ["chocolate negro", "chocolate 70%", "chocolate preto 70%", "chocolate preto 85%", "quadrado de chocolate preto"], un: 5, estado: "pronto a consumir" }],
  ["cacau em pó", 350, 20, 45, 12, 30, { aliases: ["cacau", "cacau magro", "cacau puro"], cs: 8, cc: 3, estado: "seco" }],
  ["gelatina", 60, 1.5, 14, 0, 0, { aliases: ["gelatina light", "gelatina sem açúcar", "gelatina proteica"], un: 120, estado: "pronto a consumir" }],
  ["proteína whey em pó", 380, 78, 6, 5, 1, { aliases: ["whey", "proteína em pó", "proteína whey", "scoop de whey", "proteína de soro de leite", "proteína isolada"], un: 30, cs: 10, estado: "pó" }],
  ["batido proteico", 60, 8, 4, 1, 0, { aliases: ["batido de proteína", "batido proteico pronto", "shake proteico", "batido de whey com água", "batido"], un: 250, estado: "líquido" }],
  ["café", 1, 0.1, 0, 0, 0, { aliases: ["café expresso", "café sem açúcar", "café com leite", "descafeinado"], un: 50, estado: "líquido" }],
  ["chá", 1, 0, 0.2, 0, 0, { aliases: ["infusão", "chá verde", "chá de gengibre", "infusão de gengibre", "chá de camomila", "infusão sem açúcar", "chá preto", "chá de hortelã"], un: 250, estado: "líquido" }],
  ["água", 0, 0, 0, 0, 0, { aliases: ["água com gás", "água com limão", "água morna", "água fresca"], un: 250, estado: "líquido" }],
  ["vinagre", 20, 0, 1, 0, 0, { aliases: ["vinagre de maçã", "vinagre de cidra", "vinagre balsâmico"], cs: 15, cc: 5, estado: "líquido" }],
  ["mostarda", 70, 4, 5, 4, 2, { aliases: ["mostarda de dijon"], cs: 15, cc: 5, estado: "pronto a consumir" }],
  ["ervas aromáticas", 0, 0, 0, 0, 0, { aliases: ["ervas", "salsa", "coentros", "orégãos", "oregãos", "tomilho", "alecrim", "manjericão", "louro", "pimenta", "pimenta preta", "colorau", "paprica", "páprica", "cominhos", "curcuma", "açafrão", "gengibre", "gengibre fresco", "gengibre em pó", "sal", "especiarias", "temperos", "sumo de limão q.b.", "limão q.b."], cs: 2, estado: "seco" }],
  // ---------- pratos compostos frequentes ----------
  ["panquecas de aveia", 180, 8, 22, 6, 3, { aliases: ["panqueca de aveia", "panquecas de aveia (aveia, ovo, leite)", "panquecas de aveia e banana", "panquecas de aveia e ovo", "panqueca de banana e ovo"], un: 60, estado: "cozinhado" }],
  ["salada de atum", 120, 15, 3, 5, 1, { aliases: ["salada de atum com grão", "salada de atum com grão e ovo", "salada de atum e feijão"], estado: "pronto a consumir" }],
  ["carne de porco à alentejana", 180, 16, 8, 9, 1, { aliases: ["porco à alentejana"], estado: "cozinhado" }],
  ["jardineira", 110, 9, 8, 5, 1.5, { aliases: ["jardineira de carne", "carne guisada com legumes", "guisado de carne magra", "carne estufada com legumes"], estado: "cozinhado" }],
  ["feijoada", 160, 11, 14, 6, 5, { aliases: ["feijoada de feijão branco", "feijoada magra", "feijoada sem enchidos"], estado: "cozinhado" }],
  ["bacalhau à brás", 200, 13, 12, 11, 1, { aliases: ["bacalhau à bras"], estado: "cozinhado" }],
  ["arroz de tomate", 120, 2.5, 25, 1.5, 1, { aliases: ["arroz de legumes", "arroz de cenoura", "arroz de ervilhas"], estado: "cozinhado" }],
  ["puré de legumes", 55, 1.5, 9, 1.5, 2, { aliases: ["puré de courgette", "puré de cenoura", "creme de courgette"], estado: "cozinhado" }],
  ["wrap integral", 300, 9, 50, 7, 5, { aliases: ["tortilha integral", "tortilha de trigo integral", "wrap"], un: 45, estado: "pronto a consumir" }],
];
